### ISSUE TITLE
error when running inferseq-reference

### ISSUE THREAD

**Issue by zenalapp** [durrantmm/mustache#3]
Hi! I'm trying to run mustache and can successfully run `findflanks` and `pairflanks`, but get an error when I run `inferseq-reference`:

`$ mustache inferseq-reference mustache_test_dataset.pairflanks.tsv CFT073.fna`

```
Genome has been indexed...
Aligning pairs to genome...
Traceback (most recent call last):
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/bin/mustache", line 11, in <module>
    sys.exit(cli())
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/mustache/main.py", line 116, in inferseq_reference
    max_inferseq_size, min_inferseq_size, keep_intermediate, output_file)
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/mustache/inferseqreference.py", line 34, in _inferseq_reference
    inferred_sequences = inferer.infer_sequences()
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/mustache/inferseq.py", line 52, in infer_sequences
    self.__align_pairs_to_fasta()
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/mustache/inferseq.py", line 84, in __align_pairs_to_fasta
    additional_flags='--all --score-min G,1,9'
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/mustache/bowtie2tools.py", line 60, in align_fasta_to_genome
    shell(command, read=silence)
  File "/nfs/esnitkin/bin_group/miniconda3/envs/mustache/lib/python3.6/site-packages/snakemake/shell.py", line 142, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' set -euo pipefail;  rm -f mustache.inferseq.80751361094507515469.bam.sam mustache.inferseq.80751361094507515469.bam.sam.tmp; bowtie2 --all --score-min G,1,9 --local -x mustache_test_dataset/CFT073.fna -p 1 -f -U mustache.inferseq.27504788217151935776.fasta -S mustache.inferseq.80751361094507515469.bam.sam 2> /dev/null; samtools view -h -q 1 mustache.inferseq.80751361094507515469.bam.sam 2> /dev/null 1> mustache.inferseq.80751361094507515469.bam.sam.tmp; samtools sort mustache.inferseq.80751361094507515469.bam.sam.tmp 2> /dev/null 1> mustache.inferseq.80751361094507515469.bam; samtools index mustache.inferseq.80751361094507515469.bam 2> /dev/null;rm -f mustache.inferseq.80751361094507515469.bam.sam mustache.inferseq.80751361094507515469.bam.sam.tmp ' returned non-zero exit status 127.
```

**Comment by durrantmm** [comment]
Hello, so sorry for the late response. Did you install the conda environment? If you did, you need to type `source activate mustache` before you start running it. This particular command requires bowtie2, which installing the conda environment should provide for you.

I will be uploading a new version of mustache in the coming weeks that will include automatic sequence clustering and genotyping.
